-- Expande blocklist de palavras proibidas com termos pt-BR adicionais.

insert into public.palavra_proibida (termo) values
  ('arrombado'), ('arrombada'),
  ('babaca'),
  ('boceta'),
  ('bosta'),
  ('broxa'),
  ('canalha'),
  ('corno'), ('corna'),
  ('cu'),
  ('desgraçado'), ('desgraçada'),
  ('escroto'), ('escrota'),
  ('foda'), ('foda-se'), ('fodase'),
  ('filha da puta'),
  ('lazarento'), ('lazarenta'),
  ('merdoso'), ('merdosa'),
  ('otário'), ('otaria'),
  ('piroca'),
  ('piranha'),
  ('prostituta'),
  ('putinha'),
  ('puta que pariu'),
  ('rapariga'),
  ('retardado'), ('retardada'),
  ('sacana'),
  ('safado'), ('safada'),
  ('toma no cu'),
  ('vadia'),
  ('vagabundo'), ('vagabunda'),
  ('vai se foder'),
  ('vai tomar no cu'),
  ('xoxota'),
  ('fds'),
  ('vtc'),
  ('bastardo'), ('bastarda'),
  ('lixo humano'),
  ('escória'),
  ('cuzão')
on conflict (termo) do nothing;
